
#ifndef __GNET_GPANELCLIENT_CALLID
#define __GNET_GPANELCLIENT_CALLID

namespace GNET
{

enum CallID
{
	RPC_GMYSQLSTORAGE	=	13400,
};

enum ProtocolType
{
	PROTOCOL_PANELCHALLENGE	=	13401,
	PROTOCOL_PANELRESPONSE	=	13402,
	PROTOCOL_PANELRESPONSE_RE	=	13403,
	PROTOCOL_MYSQLSTORAGE	=	13404,
	PROTOCOL_MYSQLSTORAGE_RE	=	13405,
};

};
#endif
