
#ifndef __GNET_LICENSESERVICE_CALLID
#define __GNET_LICENSESERVICE_CALLID

namespace GNET
{

enum CallID
{
};

enum ProtocolType
{
	PROTOCOL_LICENSECHALLENGE	=	13000,
	PROTOCOL_LICENSELOGIN	=	13001,
	PROTOCOL_LICENSELOGIN_RE	=	13002,
	PROTOCOL_LICENSEDATA	=	13003,
	PROTOCOL_LICENSEDATA_RE	=	13004,
	PROTOCOL_LICENSEQUIT	=	13012,
};

};
#endif
